version: '3'

services:
  baden_db:
    image: mongo:4
    container_name: baden_db
    hostname: baden_db
    restart: always
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-buffer-size: "10m"
        max-size: "200m"
    volumes:
      - /docker/data/baden/data/db:/data/db
    expose:
      - 27017

  baden_web:
    image: vdsbenoit/baden:latest
    container_name: baden_web
    hostname: baden_web
    restart: always
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-buffer-size: "10m"
        max-size: "200m"
    expose:
      - 8080
    depends_on:
      - baden_db
    networks:
      - largo

networks:
  largo:
    external:
      name: largo
