version: '3'

services:
  mongo:
    image: mongo:4
    container_name: baden_db
    hostname: baden_db
    restart: always
    cpu_shares: 512
    mem_limit: 16g
    memswap_limit: 8g
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-buffer-size: "10m"
        max-size: "200m"
    volumes:
      - /docker/data/baden/db:/data/db
    expose:
      - 27017

  web:
    image: vdsbenoit/baden:latest
    container_name: baden_web
    hostname: baden_web
    restart: always
    cpu_shares: 512
    mem_limit: 16g
    memswap_limit: 8g
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-buffer-size: "10m"
        max-size: "200m"
    expose:
      - 8080
    networks:
      - largo

  networks:
    largo:
      external:
        name: largo

